<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Asparagus</name>
   <tag></tag>
   <elementGuidId>bd9ca5a8-0deb-4e37-b0f2-0dab498542bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@href=&quot;https://qa.cert.hebtoyou.net/catalog/category/view/s/asparagus-and-artichokes/id/2344/&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
