<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save for Later</name>
   <tag></tag>
   <elementGuidId>fc0f67ca-ebbf-4f54-80d7-19293c804f93</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product-id</name>
      <type>Main</type>
      <value>436561</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-params</name>
      <type>Main</type>
      <value>{&quot;action&quot;:&quot;https://qa.cert.hebtoyou.net/wishlist/index/add/&quot;,&quot;data&quot;:{&quot;product&quot;:&quot;436561&quot;,&quot;uenc&quot;:&quot;aHR0cHM6Ly9xYS5jZXJ0LmhlYnRveW91Lm5ldC9jYXRhbG9nL2NhdGVnb3J5L3ZpZXcvcy9icm9jY29saS1hbmQtY2F1bGlmbG93ZXIvaWQvMjM0Ny8,&quot;}}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label action split wishlist-dropdown</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Save for Later
        </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/div[@class=&quot;products wrapper grid products-grid&quot;]/ol[@class=&quot;products list items product-items&quot;]/li[@class=&quot;item product product-item&quot;]/div[@class=&quot;product-item-info&quot;]/div[@class=&quot;product details product-item-details&quot;]/div[@class=&quot;product-actions clear&quot;]/div[@class=&quot;actions-secondary&quot;]/div[@class=&quot;split button wishlist active&quot;]/button[@class=&quot;label action split wishlist-dropdown&quot;]</value>
   </webElementProperties>
</WebElementEntity>
