<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1111111111111111111111111</name>
   <tag></tag>
   <elementGuidId>88bfbd6b-fc12-4155-8159-bbff53c431e3</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wishlist-name</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wishlist-id</name>
      <type>Main</type>
      <value>98</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action-keypress</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-params</name>
      <type>Main</type>
      <value>{&quot;action&quot;:&quot;https://qa.cert.hebtoyou.net/wishlist/ajax/updateProductWishlist/&quot;,&quot;data&quot;:{&quot;product&quot;:&quot;436561&quot;,&quot;uenc&quot;:&quot;aHR0cHM6Ly9xYS5jZXJ0LmhlYnRveW91Lm5ldC9jYXRhbG9nL2NhdGVnb3J5L3ZpZXcvcy9icm9jY29saS1hbmQtY2F1bGlmbG93ZXIvaWQvMjM0Ny8,&quot;,&quot;wishlist_id&quot;:&quot;98&quot;}}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>add-to-wishlist-with-ajax</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>11111111111111111111111111111111111111111111111111111111111</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            11111111111111111111111111111111111111111111111111111111111
                    </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/div[@class=&quot;products wrapper grid products-grid&quot;]/ol[@class=&quot;products list items product-items&quot;]/li[@class=&quot;item product product-item&quot;]/div[@class=&quot;product-item-info&quot;]/div[@class=&quot;product details product-item-details&quot;]/div[@class=&quot;product-actions clear&quot;]/div[@class=&quot;actions-secondary&quot;]/div[@class=&quot;split button wishlist active&quot;]/div[@class=&quot;wishlist-dropdown-block items active&quot;]/ul[@class=&quot;items-lists&quot;]/li[@class=&quot;item checked-item&quot;]/span[@class=&quot;wishlist-name&quot;]</value>
   </webElementProperties>
</WebElementEntity>
